version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev_data
      - POSTGRES_PASSWORD=Abcdevpoc
      - POSTGRES_INITDB_WAL_LEVEL=logical #required for the debezium connector



  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    hostname: zookeeper


  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=172.17.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=DataChange:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181


  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev_data
      - MONGO_INITDB_ROOT_PASSWORD=Abcdevpoc


  debezium-connector:
    image: debezium/connect:latest
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=debezium-group
      - CONFIG_STORAGE_TOPIC=debezium-configs
      - OFFSET_STORAGE_TOPIC=debezium-offsets
      - STATUS_STORAGE_TOPIC=debezium-status
      - CONNECT_REST_ADVERTISED_HOST_NAME=debezium-connector
      - CONNECT_REST_PORT=8083
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

    volumes:
      - ./db-config.json:/kafka/db-config.json

#flink cluster
  jobmanager:
    image: flink:1.16.0
    expose:
      - "6123"
    ports:
      - 8081:8081
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - JOB_MANAGER_RPC_PORT=6123
      - JOB_MANAGER_HEAP_MEMORY=1024m
    volumes:
      - ./FlinkKafka.jar:/opt/flink/FlinkKafka.jar

    command: jobmanager

  taskmanager:
    image: flink:1.16.0
    depends_on:
      - jobmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./FlinkKafka.jar:/opt/flink/FlinkKafka.jar

    command: taskmanager



#monitoring mongo db metrics
  mongodb-exporter:
    image: percona/mongodb_exporter:0.37.0

    ports:
      - 9216:9216

    environment:
      - MONGODB_URI=mongodb://dev_data:Abcdevpoc@172.17.0.1:27017
    command:
      - "--collect-all"

    depends_on:
      - mongodb

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      -  '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - mongodb-exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
